name: Classes
version: '${project.version}'
main: dev.efekos.classes.Main
api-version: '1.20'
description: Make custom classes in your server!
author: efekos
permissions:
  classes.info:
    description: Allows to use /class info
    default: true
  classes.join:
    description: Allows to use /class join
    default: true
  classes.kit.get:
    description: Allows to use /class kit get
    default: true
  classes.leave:
    description: Allows to use /class leave
    default: true
  classes.members:
    description: Allows to use /class members
    default: true
  classes.modifiers:
    description: Allows to use /class modifiers
    default: true
  classes.perks:
    description: Allows to use /class perks
    default: true